name: Vitest

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

env:
  CI: ""

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Use npm 10
        run: npm install -g npm@^10
      - name: Install
        run: npm ci --include=optional --no-audit --no-fund
      - name: Run Vitest
        run: npm run test
